name: desktop_recorder
description: A desktop Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2

  # third party
  ffmpeg_kit_flutter: ^5.1.0
  file_picker: ^5.2.5
  get: ^4.6.5
#  path_provider: ^2.0.13
  process_run: ^0.12.5+2
  window_manager: ^0.3.1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ffmpeg.exe
